[package]
name = "qexed_chat"
version = "0.1.0"
edition = "2024"
[dependencies]
# 程序级依赖


# 内部库依赖
qexed_tcp_connect = { workspace = true }
qexed_packet = { workspace = true }
qexed_protocol = { workspace = true }
qexed_task = {workspace = true}
qexed_config = {workspace = true}
qexed_player.workspace = true
qexed_nbt.workspace = true
qexed_command.workspace = true
# 第三方依赖
anyhow = { workspace = true }
tokio  = { workspace = true }
log.workspace = true
tklog.workspace = true
uuid.workspace = true
bytes.workspace = true
thiserror.workspace = true
async-trait.workspace = true
dashmap.workspace = true