[package]
name = "qexed_rule"
version = "0.1.0"
edition = "2024"
[dependencies]
qexed_command.workspace = true
qexed_task.workspace = true
qexed_config.workspace = true
qexed_shared.workspace = true
tokio.workspace = true
log.workspace = true
serde.workspace = true
anyhow.workspace = true
uuid.workspace = true