[package]
name = "qexed_packet"
version = "0.1.0"
edition = "2024"

[dependencies]
qexed_nbt.workspace = true
anyhow.workspace = true
bytes.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
thiserror.workspace = true
byteorder.workspace = true