[package]
name = "qexed_one"
version = "0.1.0"
edition = "2024"
# build = "build.rs"
[package.metadata.android]
# 应用的唯一标识（通常使用反向域名格式）
package = "com.qexed.qexed_one"
# 指定编译的架构（可同时编译多个）
build_targets = ["aarch64-linux-android", "armv7-linux-androideabi"]
# 应用在桌面上显示的名称
label = "Qexed One"

[[bin]]
name = "qexed_one"
path = "src/main.rs"
[dependencies]
# 程序级依赖
qexed_player_list = { workspace = true }
qexed_tcp_connect_app = { workspace = true }
qexed_status = {workspace = true}
qexed_whitelist = {workspace = true}
qexed_blacklist = {workspace = true}
qexed_game_logic.workspace = true
qexed_ping.workspace = true
qexed_heartbeat.workspace = true
qexed_chat.workspace = true
qexed_entity_id_allocator.workspace = true
qexed_packet_split.workspace = true
qexed_command.workspace = true
qexed_rule.workspace = true
qexed_chunk.workspace = true
qexed_title.workspace = true
# 内部库依赖
qexed_tcp_connect = { workspace = true }
qexed_task = {workspace = true}
qexed_shared.workspace = true
qexed_config = {workspace = true}
qexed_cli = {workspace = true}
# 第三方依赖
anyhow = { workspace = true }
tokio  = { workspace = true }
log.workspace = true
tklog.workspace = true
chrono.workspace = true
[build-dependencies]
vergen = "8"  # 用于注入构建信息
chrono.workspace = true